export const ADD_INGREDIENT_TO_CONSTRUCTOR = 'ADD_INGREDIENT_TO_CONSTRUCTOR';
export const REMOVE_INGREDIENT_FROM_CONSTRUCTOR = 'REMOVE_INGREDIENT_FROM_CONSTRUCTOR';

export const PLACE_INGREDIENT_BEFORE = 'PLACE_INGREDIENT_BEFORE';
export const PLACE_INGREDIENT_AFTER = 'PLACE_INGREDIENT_AFTER';