export const ADD_INGREDIENT_TO_CONSTRUCTOR = 'ADD_INGREDIENT_TO_CONSTRUCTOR';
export const REMOVE_INGREDIENT_FROM_CONSTRUCTOR = 'REMOVE_INGREDIENT_FROM_CONSTRUCTOR';
export const WRAP_INGREDIENTS_IN_CONSTRUCTOR = 'WRAP_INGREDIENTS_IN_CONSTRUCTOR';
